### ISSUE TITLE
read.me

### ISSUE THREAD

**Issue by baov** [neftx/generic-form#1]
### user guide
> npm i @neftx/generic-from --save-dev 
should be 
> npm i @neftx/generic-form --save-dev

### before using
> "node node_modules/@neftx/generic-form/generate-elements.js
should be
> "node node_modules/@neftx/generic-form/generate-elements.js"

**Comment by kpsrinivas** [comment]
What exactly is the issue?

**Comment by baov** [comment]
Hi, 
it's just misspelled in readme document for user like us.
Thanks for your reply

**Comment by kpsrinivas** [comment]
Thanks!
